# Generated by Django 5.1.5 on 2025-04-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('PROF', 'PROFESOR'), ('ESTU', 'Estudiante'), ('VIST', 'Visitante')], max_length=4),
        ),
    ]
