# Generated by Django 5.1.5 on 2025-04-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('PROF', 'Profesor'), ('ESTU', 'Estudiante')], max_length=4),
        ),
    ]
