# Generated by Django 5.1.5 on 2025-04-05 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('idActividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fechaEntrega', models.DateField()),
                ('porcentajeAcademico', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='%')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Acudientes',
            fields=[
                ('idAcudiente', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=15, unique=True)),
                ('contactoAuxiliar', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(default=None, max_length=100)),
                ('municipio', models.CharField(default=None, max_length=100)),
                ('foto', models.ImageField(default=None, upload_to='acudientes')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Acudiente',
                'verbose_name_plural': 'Acudientes',
                'db_table': 'Acudientes',
            },
        ),
        migrations.CreateModel(
            name='Grados',
            fields=[
                ('idGrado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B'), ('4A', '4B'), ('5A', '5A'), ('5B', '5B')], max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'db_table': 'Grados',
            },
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('idMateria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('idPQRS', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCompleto', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('grado', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('respuesta', models.BooleanField(default=False)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PQRS',
                'verbose_name_plural': 'PQRS',
                'db_table': 'PQRS',
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('PROF', 'Profesor'), ('EST', 'Estudiante')], max_length=4),
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('idEstudiante', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(default=None, max_length=100)),
                ('municipio', models.CharField(default=None, max_length=100)),
                ('foto', models.ImageField(default=None, upload_to='estudiantes')),
                ('fechaNacimiento', models.DateField(default=None)),
                ('edad', models.CharField(default=None, max_length=3)),
                ('tipoSangre', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default=None, max_length=3)),
                ('enfermedadDiscapacidad', models.CharField(default=None, max_length=200)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fkAcudiente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.acudientes', verbose_name='Acudiente')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.usuario')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('idEvaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=5)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('calificado', models.BooleanField(default=False)),
                ('fkActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.actividades', verbose_name='Actividad')),
                ('fkEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.estudiantes', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Evaluacion',
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'Evaluaciones',
            },
        ),
        migrations.AddField(
            model_name='actividades',
            name='fkGrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.grados', verbose_name='Grado'),
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('idInscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=True)),
                ('fkEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.estudiantes', verbose_name='Estudiante')),
                ('fkGrado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.grados', verbose_name='Grado')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'Inscripciones',
            },
        ),
        migrations.AddField(
            model_name='actividades',
            name='fkMateria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.materias', verbose_name='Materia'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('idPost', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('fkGrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.grados', verbose_name='Grado')),
                ('fkMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.materias', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fkEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.estudiantes', verbose_name='Estudiante')),
                ('fkGrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.grados', verbose_name='Grado')),
                ('fkMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.materias', verbose_name='Materia')),
                ('fkPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'Comentarios',
            },
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('idProfesor', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(default=None, max_length=100)),
                ('municipio', models.CharField(default=None, max_length=100)),
                ('fechaNacimiento', models.DateField(default=None)),
                ('edad', models.CharField(default=None, max_length=3)),
                ('foto', models.ImageField(default=None, upload_to='profesores')),
                ('especialidad1', models.CharField(max_length=100)),
                ('especialidad2', models.CharField(blank=True, max_length=100, null=True)),
                ('especialidad3', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.usuario')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'Profesores',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='fkProfesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.profesores', verbose_name='Profesor'),
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('idPensum', models.AutoField(primary_key=True, serialize=False)),
                ('fkGrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.grados', verbose_name='Grado')),
                ('fkMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.materias', verbose_name='Materia')),
                ('fkProfesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.profesores', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Pensum',
                'verbose_name_plural': 'Pensum',
                'db_table': 'Pensum',
            },
        ),
        migrations.CreateModel(
            name='Inasistencias',
            fields=[
                ('idInasistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInasistencia', models.DateField(default=None)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fotoExcusa', models.ImageField(blank=True, default=None, null=True, upload_to='excusas')),
                ('soporteExcusa', models.BooleanField(default=False, verbose_name='Soporte Excusa')),
                ('fkEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.estudiantes', verbose_name='Estudiante')),
                ('fkGrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.grados', verbose_name='Grado')),
                ('fkMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.materias', verbose_name='Materia')),
                ('fkProfesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.profesores', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Inasistencia',
                'verbose_name_plural': 'Inasistencias',
                'db_table': 'Inasistencias',
            },
        ),
        migrations.CreateModel(
            name='faltasDisciplinarias',
            fields=[
                ('idFaltaDisciplinaria', models.AutoField(primary_key=True, serialize=False)),
                ('fechaFaltaDisciplinaria', models.DateField(default=None)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fotoFaltaDisciplinaria', models.ImageField(blank=True, default=None, null=True, upload_to='Faltas Disciplinarias')),
                ('soporteFaltaDisciplinaria', models.BooleanField(default=False, verbose_name='Soporte Falta Disciplinaria')),
                ('fkEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.estudiantes', verbose_name='Estudiante')),
                ('fkGrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.grados', verbose_name='Grado')),
                ('fkMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.materias', verbose_name='Materia')),
                ('fkProfesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.profesores', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Falta Disciplinaria',
                'verbose_name_plural': 'Faltas Disciplinarias',
                'db_table': 'Faltas Disciplinarias',
            },
        ),
        migrations.CreateModel(
            name='CantidadInasistencias',
            fields=[
                ('idCantidadInasistencias', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad Inasistencias')),
                ('fkEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.estudiantes', verbose_name='Estudiante')),
                ('fkGrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.grados', verbose_name='Grado')),
                ('fkMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.materias', verbose_name='Materia')),
                ('fkProfesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.profesores', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Cantidad Inasistencia',
                'verbose_name_plural': 'Cantidad Inasistencias',
                'db_table': 'Cantidad Inasistencias',
            },
        ),
        migrations.CreateModel(
            name='CantidadFaltasDisciplinarias',
            fields=[
                ('idCantidadFaltasDisciplinarias', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad Inasistencias')),
                ('fkEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.estudiantes', verbose_name='Estudiante')),
                ('fkGrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.grados', verbose_name='Grado')),
                ('fkMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.materias', verbose_name='Materia')),
                ('fkProfesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.profesores', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Cantidad Falta Disciplinaria',
                'verbose_name_plural': 'Cantidad Faltas Disciplinarias',
                'db_table': 'Cantidad Faltas Disciplinarias',
            },
        ),
        migrations.AddField(
            model_name='actividades',
            name='fkProfesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.profesores', verbose_name='Profesor'),
        ),
        migrations.CreateModel(
            name='Promedio',
            fields=[
                ('idPromedio', models.AutoField(primary_key=True, serialize=False)),
                ('promedio', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True)),
                ('fkEstudiante', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.estudiantes', verbose_name='Estudiante')),
                ('fkGrado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.grados', verbose_name='Grado')),
                ('fkMateria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.materias', verbose_name='Materia')),
                ('fkProfesor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.profesores', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Promedio',
                'verbose_name_plural': 'Promedios',
                'db_table': 'Promedios',
            },
        ),
    ]
