# Generated by Django 5.1.5 on 2025-04-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0006_grado_estudiante_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='grado',
            name='estudiantes',
            field=models.ManyToManyField(related_name='grados', to='myColegioDjango.estudiante'),
        ),
        migrations.AddField(
            model_name='grado',
            name='profesores',
            field=models.ManyToManyField(related_name='grados', to='myColegioDjango.profesor'),
        ),
    ]
