# Generated by Django 5.1.5 on 2025-04-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0007_grado_estudiantes_grado_profesores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='grados', to='myColegioDjango.estudiante'),
        ),
        migrations.AlterField(
            model_name='grado',
            name='nombre',
            field=models.CharField(choices=[('1A', 'Primero A'), ('1B', 'Primero B'), ('2A', 'Segundo A'), ('2B', 'Segundo B'), ('3A', 'Tercero A'), ('3B', 'Tercero B'), ('4A', 'Cuarto A'), ('4B', 'Cuarto B'), ('5A', 'Quinto A'), ('5B', 'Quinto B'), ('6A', 'Sexto A'), ('6B', 'Sexto B'), ('7A', 'Séptimo A'), ('7B', 'Séptimo B'), ('8A', 'Octavo A'), ('8B', 'Octavo B'), ('9A', 'Noveno A'), ('9B', 'Noveno B'), ('10A', 'Décimo A'), ('10B', 'Décimo B'), ('11A', 'Once A'), ('11B', 'Once B')], max_length=20),
        ),
        migrations.AlterField(
            model_name='grado',
            name='profesores',
            field=models.ManyToManyField(blank=True, related_name='grados', to='myColegioDjango.profesor'),
        ),
    ]
