# Generated by Django 5.1.5 on 2025-04-07 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0009_alter_grado_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='nombre',
            field=models.CharField(choices=[('', 'Seleccione un grado'), ('1A Primero A', 'Primero A'), ('1B Primero B', 'Primero B'), ('2A', 'Segundo A'), ('2B', 'Segundo B'), ('3A', 'Tercero A'), ('3B', 'Tercero B'), ('4A', 'Cuarto A'), ('4B', 'Cuarto B'), ('5A', 'Quinto A'), ('5B', 'Quinto B'), ('6A', 'Sexto A'), ('6B', 'Sexto B'), ('7A', 'Séptimo A'), ('7B Séptimo B', 'Séptimo B'), ('8A', 'Octavo A'), ('8B', 'Octavo B'), ('9A', 'Noveno A'), ('9B', 'Noveno B'), ('10A', 'Décimo A'), ('10B', 'Décimo B'), ('11A', 'Once A'), ('11B', 'Once B')], max_length=20),
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estudiantes', models.ManyToManyField(to='myColegioDjango.estudiante')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.profesor')),
            ],
        ),
    ]
