# Generated by Django 5.2 on 2025-04-14 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0011_asignatura_grado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='grado',
            name='estudiantes',
        ),
        migrations.RemoveField(
            model_name='grado',
            name='profesores',
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, to='myColegioDjango.estudiante'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myColegioDjango.profesor'),
        ),
        migrations.AlterField(
            model_name='grado',
            name='nombre',
            field=models.CharField(choices=[('Primero', 'Primero'), ('Segundo', 'Segundo'), ('Tercero', 'Tercero'), ('Cuarto', 'Cuarto'), ('Quinto', 'Quinto'), ('Sexto', 'Sexto'), ('Séptimo', 'Séptimo'), ('Octavo', 'Octavo'), ('Noveno', 'Noveno'), ('Décimo', 'Décimo'), ('Undécimo', 'Undécimo')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
