# Generated by Django 5.1.5 on 2025-04-19 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0012_remove_asignatura_grado_remove_grado_estudiantes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Estudiantes',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='usuario',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.usuarios')),
            ],
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='Grado',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
