# Generated by Django 5.1.5 on 2025-04-19 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0013_rename_profesor_estudiantes_remove_estudiante_grado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('idMateria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='Grados',
            fields=[
                ('idGrado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B'), ('4A', '4B'), ('5A', '5A'), ('5B', '5B')], max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'db_table': 'Grados',
            },
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('idActividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fechaEntrega', models.DateField()),
                ('porcentajeAcademico', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='%')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fkProfesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.profesores', verbose_name='Profesor')),
                ('fkAsignaturas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.asignaturas', verbose_name='Materia')),
                ('fkGrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.grados', verbose_name='Grado')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('idEvaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=5)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('calificado', models.BooleanField(default=False)),
                ('fkActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.actividades', verbose_name='Actividad')),
                ('fkEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.estudiantes', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Evaluacion',
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('idInscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=True)),
                ('fkEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.estudiantes', verbose_name='Estudiante')),
                ('fkGrado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.grados', verbose_name='Grado')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('idPensum', models.AutoField(primary_key=True, serialize=False)),
                ('fkAsignaturas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.asignaturas', verbose_name='Materia')),
                ('fkGrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.grados', verbose_name='Grado')),
                ('fkProfesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.profesores', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Pensum',
                'verbose_name_plural': 'Pensum',
                'db_table': 'Pensum',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('idPost', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('fkAsignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.asignaturas', verbose_name='Materia')),
                ('fkGrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.grados', verbose_name='Grado')),
                ('fkProfesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.profesores', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fkAsignaturas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.asignaturas', verbose_name='Materia')),
                ('fkEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.estudiantes', verbose_name='Estudiante')),
                ('fkGrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.grados', verbose_name='Grado')),
                ('fkPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'Comentarios',
            },
        ),
        migrations.CreateModel(
            name='Promedio',
            fields=[
                ('idPromedio', models.AutoField(primary_key=True, serialize=False)),
                ('promedio', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True)),
                ('fkAsignaturas', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.asignaturas', verbose_name='Materia')),
                ('fkEstudiante', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.estudiantes', verbose_name='Estudiante')),
                ('fkGrado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.grados', verbose_name='Grado')),
                ('fkProfesor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.profesores', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Promedio',
                'verbose_name_plural': 'Promedios',
                'db_table': 'Promedios',
            },
        ),
    ]
