# Generated by Django 5.1.5 on 2025-04-19 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0014_asignaturas_grados_actividades_evaluaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Primero', 'Primero'), ('Segundo', 'Segundo'), ('Tercero', 'Tercero'), ('Cuarto', 'Cuarto'), ('Quinto', 'Quinto'), ('Sexto', 'Sexto'), ('Séptimo', 'Séptimo'), ('Octavo', 'Octavo'), ('Noveno', 'Noveno'), ('Décimo', 'Décimo'), ('Undécimo', 'Undécimo')], max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='evaluaciones',
            name='fkActividad',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='fkAsignaturas',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fkAsignatura',
        ),
        migrations.RemoveField(
            model_name='promedio',
            name='fkAsignaturas',
        ),
        migrations.RemoveField(
            model_name='pensum',
            name='fkAsignaturas',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='fkEstudiante',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='fkGrado',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='fkPost',
        ),
        migrations.RemoveField(
            model_name='evaluaciones',
            name='fkEstudiante',
        ),
        migrations.RemoveField(
            model_name='inscripciones',
            name='fkGrado',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fkGrado',
        ),
        migrations.RemoveField(
            model_name='pensum',
            name='fkGrado',
        ),
        migrations.RemoveField(
            model_name='promedio',
            name='fkGrado',
        ),
        migrations.RemoveField(
            model_name='inscripciones',
            name='fkEstudiante',
        ),
        migrations.RemoveField(
            model_name='pensum',
            name='fkProfesor',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fkProfesor',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='promedio',
            name='fkProfesor',
        ),
        migrations.RemoveField(
            model_name='promedio',
            name='fkEstudiante',
        ),
        migrations.RenameModel(
            old_name='Estudiantes',
            new_name='Profesor',
        ),
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myColegioDjango.usuario')),
                ('grado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myColegioDjango.grado')),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myColegioDjango.profesor')),
                ('estudiantes', models.ManyToManyField(blank=True, to='myColegioDjango.estudiante')),
            ],
        ),
        migrations.DeleteModel(
            name='Actividades',
        ),
        migrations.DeleteModel(
            name='Asignaturas',
        ),
        migrations.DeleteModel(
            name='Comentarios',
        ),
        migrations.DeleteModel(
            name='Evaluaciones',
        ),
        migrations.DeleteModel(
            name='Grados',
        ),
        migrations.DeleteModel(
            name='Inscripciones',
        ),
        migrations.DeleteModel(
            name='Pensum',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Profesores',
        ),
        migrations.DeleteModel(
            name='Promedio',
        ),
    ]
