# Generated by Django 5.1.5 on 2025-04-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0017_grados_fechacreacion_alter_grados_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
