# Generated by Django 5.1.5 on 2025-04-19 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0020_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='profesor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='myColegioDjango.profesor'),
            preserve_default=False,
        ),
    ]
