# Generated by Django 5.1.5 on 2025-04-19 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0021_asignatura_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='myColegioDjango.asignatura'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='myColegioDjango.asignatura'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas', to='myColegioDjango.profesor'),
        ),
    ]
