# Generated by Django 5.1.5 on 2025-04-19 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0022_blog_asignatura_alter_actividad_asignatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiante', to='myColegioDjango.grados'),
        ),
        migrations.AlterField(
            model_name='grados',
            name='nombre',
            field=models.CharField(choices=[('Primero A', 'Primero A'), ('Primero B', 'Primero B'), ('Segundo A', 'Segundo A'), ('Segundo B', 'Segundo B'), ('Tercero A', 'Tercero A'), ('Tercero B', 'Tercero B'), ('Cuarto A', 'Cuarto A'), ('Cuarto B', 'Cuarto B'), ('Quinto A', 'Quinto A'), ('Quinto B', 'Quinto B'), ('Sexto A', 'Sexto A'), ('Sexto B', 'Sexto B'), ('Séptimo A', 'Séptimo A'), ('Séptimo B', 'Séptimo B'), ('Octavo A', 'Octavo A'), ('Octavo B', 'Octavo B'), ('Noveno A', 'Noveno A'), ('Noveno B', 'Noveno B'), ('Décimo A', 'Décimo A'), ('Décimo B', 'Décimo B'), ('Undécimo A', 'Undécimo A'), ('Undécimo B', 'Undécimo B')], max_length=20),
        ),
    ]
