# Generated by Django 5.1.5 on 2025-04-19 23:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0023_alter_estudiante_grado_alter_grados_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='myColegioDjango.grados'),
        ),
    ]
