# Generated by Django 5.2 on 2025-05-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0024_usuario_fechacreacion_alter_estudiante_grado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nick',
        ),
    ]
