# Generated by Django 5.2 on 2025-05-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0026_aviso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aviso',
        ),
    ]
