# Generated by Django 5.2 on 2025-05-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0027_delete_aviso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grados',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
