# Generated by Django 5.2 on 2025-05-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0028_alter_grados_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
