# Generated by Django 5.2 on 2025-05-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0030_alter_usuario_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='asignatura',
        ),
    ]
