# Generated by Django 5.2 on 2025-05-19 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0031_remove_actividad_asignatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='myColegioDjango.asignatura'),
        ),
    ]
