# Generated by Django 5.2 on 2025-05-21 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0033_remove_blog_asignatura_blog_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='grados',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='myColegioDjango.grados'),
        ),
    ]
