# Generated by Django 5.2 on 2025-05-22 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0034_blog_grados'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='grados',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas', to='myColegioDjango.grados'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='myColegioDjango.asignatura', unique=True),
        ),
    ]
