# Generated by Django 5.2 on 2025-05-22 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0035_asignatura_grados_alter_actividad_asignatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignatura',
            old_name='grados',
            new_name='grupos',
        ),
    ]
