# Generated by Django 5.2 on 2025-05-22 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0036_rename_grados_asignatura_grupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='myColegioDjango.asignatura'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
