# Generated by Django 5.2 on 2025-05-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0037_alter_actividad_asignatura_alter_actividad_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignatura',
            old_name='grupos',
            new_name='grados',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
