# Generated by Django 5.1.5 on 2025-06-03 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0038_rename_grupos_asignatura_grados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grados',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grados', to='myColegioDjango.profesor'),
        ),
    ]
