# Generated by Django 5.1.6 on 2025-07-10 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0039_grados_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='grados',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grados', to='myColegioDjango.estudiante'),
        ),
    ]
