# Generated by Django 5.1.6 on 2025-07-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myColegioDjango', '0040_grados_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grados',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='grados',
            name='estudiante',
            field=models.ManyToManyField(blank=True, related_name='grados', to='myColegioDjango.estudiante'),
        ),
    ]
